config/routes.rb
Rails.application.routes.draw do
    resources :subscribers
    # mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'registrations' }

    get '/' => 'application#index', as: 'index'
    get '/account' => 'users#show', as: 'account'
    get 'designs' => 'designs#show_all', as: 'designs'
    get 'designer/:id' => 'designs#designer', as: 'designer'
    post 'designs' => 'designs#create'

    get 'designs/filter' => 'designs#filter_gender'
    get 'designs/:gender' => 'designs#filter_season'

    get 'designs/:gender/:season' => 'designs#filter', as: 'filter'

    mount Commontator::Engine => '/commontator'

    delete 'design/:id/delete' => 'designs#destroy', as: 'destroy_design'

    resources :designs, path: 'design', except: [:index]
    put	'/design/:id/like' =>	'designs#upvote', as: 'like'
    put	'/design/:id/dislike' => 'designs#downvote', as: 'dislike'
end

app/models/design.rb
class Design < ApplicationRecord
    is_impressionable
    acts_as_votable
    belongs_to :user
    validates :title, presence: true,
                      uniqueness: true, length: { maximum: 30, minimum: 4 }
    validates :description, presence: true,
                            length: { maximum: 120, minimum: 5 }, uniqueness: true
    validates :image, presence: true
    validates :gender, presence: true
    validates :season, presence: true
    has_attached_file :image, content_type: %w(image/jpeg image/jpg image/png image/gif),
                              message: 'is not gif, png, jpg, or jpeg.',
                              styles: {
                                  medium: '300x300>',
                                  thumb: {
                                      geometry: '100x100>',
                                      processor_options: {
                                          compression: {
                                              png: false,
                                              jpeg: '-copy none -optimize'
                                          }
                                      }
                                  }
                              },
                              processors: [:thumbnail, :compression]
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    attr_accessor :base64_thumbnail_image
    acts_as_commontable

    def save_base64_thumbnail_image
        if base64_thumbnail_image.present?
            file_path = "tmp/foo_bar_thumbnail_image_#{id}.png"
            File.open(file_path, 'wb') { |f| f.write(Base64.decode64(base64_thumbnail_image)) }
            # set the paperclip attribute and let it do its thing
            self.thumbnail_image = File.new(file_path, 'r')
        end
      end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
    before_action :find_params, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :propetary, only: [:show]
    before_action :authenticate_user!, except: [:index, :designs]
    before_action :authenticate_propetary, only: [:edit, :update, :Destroy]

    def show
        commontator_thread_show(@design)
    end

    def filter_gender
    end

    def filter_season
        @gender = gender_params
    end

    def filter
        @gender = gender_params
        @season = season_params
        @designs = if @gender == 'all' && @season == 'all'
                       Design.all
                   elsif @gender == 'all'
                       Design.where(season: @season)
                   elsif @season == 'all'
                       Design.where(gender: @gender)
                   else
                       Design.where(gender: @gender, season: @season)
                     end
    end

    def create
        @design = current_user.designs.new(design_params)
        respond_to do |format|
            if @design.save
                format.html { redirect_to @design, notice: "great #{current_user.name}! Your design was created successfully." }
                format.json { render action: 'show', status: :created, location: @design }
            else
                format.html { redirect_to new_design_path, flash: { error: @design.errors.full_messages.join(', ') } }
                format.json { render json: @design.errors, status: :unprocessable_entity }
            end
        end
    end

    def show_all
        @designs = Design.page(params[:page]).per(9)
    end

    def update
        if  @design.update(design_params)
            redirect_to @design
        else
            redirect_to '/'
          end
    end

    def destroy
        @design.destroy
        redirect_to '/designs'
    end

    def upvote
        @design.upvote_by current_user
        redirect_to '/designs'
    end

    def downvote
        @design.downvote_by current_user
        redirect_to '/designs'
    end

    def designer
        @user = User.find(params[:id])
        @designs = Design.where(user_id:  @user.id)
    end

    private

    def design_params
        params.require(:design).permit(:title, :description, :image, :user_id, :season, :gender)
    end

    def find_params
        @design = Design.find(params[:id])
    end

    def gender_params
        params[:gender]
    end

    def season_params
        params[:season]
    end

    def propetary
        @propetary = User.where(id: @design.user_id)
    end

    def authenticate_propetary
        @design = find_params
        redirect_to @design if @design.user_id != current_user.id
    end
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_edit.html.erb
   <div class="modal-content">
hy
        </div>

app/views/designs/designer.html.erb
<div class="row">
    <% @designs.each do |design| %>
    <div class="col s12 m4">
        <div class="circle-designs-card card ">
            <div class="card-image image-medium">
                <%= link_to design_path(design, design.user_id) do %>
                <%=image_tag design.image.url(:medium) %>
                <%end%>
            </div>
            <div class="card-content">
                <div class="col s12 m4 top">
                    <% ellipsis = design.title.bytesize  %>
                    <% if ellipsis == 9 %>
                    <%= design.title %>
                    <% elsif ellipsis < 9 %>
                    <%= design.title %>
                    <%else%>
                    <%= design.title.split("").values_at(0..8).join.ljust(12, "...")%>
                    <%end%>
                </div>
                <div class="col s12 m4 top">
                    <%= link_to like_path(design), method: :put do %>
                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                    <%end%>
                    <%= design.get_upvotes.size %>|
                    <%= link_to dislike_path(design), method: :put do %>
                    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                    <%= design.get_downvotes.size %>
                    <%end%>
                </div>
                <div class="col s12 m3 top">
                    <% @user = User.where(id: design.user_id).each do |user| %>
                    <%= link_to designer_path(user) do%>
                    <%=user.name%>
                    <%end%>
                    <%end%>
                </div>
                <div class="col s12 m1">
                    <%= "#{design.impressionist_count}" %>
                </div>
            </div>
        </div>
    </div>

    <%end%>

</div>

app/views/designs/designs.html.erb
<div class="row">
    <% @designs.each do |design| %>
    <div class="col s12 m4">
        <div class="circle-designs-card card ">
            <div class="card-image image-medium">
                <%= link_to design_path(design, design.user_id) do %>
                <%=image_tag design.image.url(:medium) %>
                <%end%>
            </div>
            <div class="card-content">
                <div class="col s12 m4 top">
                    <% ellipsis = design.title.bytesize  %>
                    <% if ellipsis == 9 %>
                    <%= design.title %>
                    <% elsif ellipsis < 9 %>
                    <%= design.title %>
                    <%else%>
                    <%= design.title.split("").values_at(0..8).join.ljust(12, "...")%>
                    <%end%>
                </div>
                <div class="col s12 m4 top">
                    <%= link_to like_path(design), method: :put do %>
                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                    <%end%>
                    <%= design.get_upvotes.size %>|
                    <%= link_to dislike_path(design), method: :put do %>
                    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                    <%= design.get_downvotes.size %>
                    <%end%>
                </div>
                <div class="col s12 m3 top">
                    <% @user = User.where(id: design.user_id).each do |user| %>
                    <%= link_to designer_path(user) do%>
                    <%=user.name%>
                    <%end%>
                    <%end%>
                </div>
                <div class="col s12 m1">
                    <%= "#{design.impressionist_count}" %>
                </div>
            </div>
        </div>
    </div>

    <%end%>

</div>
<%= paginate @designs %>

app/views/designs/filter.html.erb
<div class="container">
  <% @designs.each do |design| %>
<div class="row">
       <div class="s12 m6 l3">
         <div class="card">
           <div class="card-image">
             <%= link_to design_path(design, design.user_id) do %>
             <%=image_tag design.image.url %>
              <%end%>
             <span class="card-title"></span>
           </div>
           <div class="card-content">
             <%=design.title%>
           </div>
         </div>
       </div>
     </div>
     <%= link_to like_path(design), method: :put do %>
   <i class="fa fa-thumbs-up" aria-hidden="true"></i>

 <%= design.get_upvotes.size %>|
 <%= link_to dislike_path(design), method: :put do %>
   <i class="fa fa-thumbs-down" aria-hidden="true"></i>

 <%= design.get_downvotes.size %>

<%end%>
<%end%>
<%end%>
</div>

app/views/designs/filter_gender.html.erb
<div class="row">
  <div class="filter-responsive col s12 m6 center center">
      <%= link_to("all") do%>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>all gender</h2>
       </div>
       <%end%>
  </div>
  </div>

<div class="filter-responsive col s12 m6 center">

  <%= link_to("male") do%>
<div class="filter">
<%=image_tag 'background', class: "z-depth-2"%>
   <div class="text center">
      <h2>male</h2>
   </div>
</div>
<%end%>
</div>



<div class="filter-responsive col s12 m6 center">
  <%= link_to("female") do%>
<div class="filter">
<%=image_tag 'background', class: "z-depth-2"%>
   <div class="text center">
      <h2>female</h2>
   </div>
</div>
<%end%>
  </div>


<div class="filter-responsive col s12 m6 center">
  <%= link_to("genderless") do%>
<div class="filter">
<%=image_tag 'background', class: "z-depth-2"%>
   <div class="text center">
      <h2>genderless</h2>
   </div>
   <%end%>
</div>
    </div>

</div>

app/views/designs/filter_season.html.erb
<div class="row center">
  <div class="filter-responsive col s12 m6">
        <%= link_to filter_path(@gender, :season => "all") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>all season</h2>
       </div>
       <%end%>
  </div>
  </div>
  <div class="filter-responsive col s12 m6">
        <%= link_to filter_path(@gender, :season => "spring") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>spring</h2>
       </div>
       <%end%>
  </div>
  </div>
  <div class="filter-responsive col s12 m6">
      <%= link_to filter_path(@gender, :season => "summer") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>summer</h2>
       </div>
       <%end%>
  </div>
  </div>
  <div class="filter-responsive col s12 m6">
      <%= link_to  filter_path(@gender, :season => "auturmn") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>auturmn</h2>
       </div>
       <%end%>
  </div>
  </div>
  <div class="filter-responsive col s12 m6">
      <%= link_to filter_path(@gender, :season => "winter") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>winter</h2>
       </div>
       <%end%>
  </div>
  </div>
  <div class="filter-responsive col s12 m6">
      <%= link_to filter_path(@gender, :season => "no season") do %>
  <div class="filter">
    <%=image_tag 'background', class: "z-depth-2"%>
       <div class="text center">
          <h2>no season</h2>
       </div>
       <%end%>
  </div>
  </div>
</div>

app/views/designs/new.html.erb
<div class="container">
    <%= form_for [@design] do |f| %>
    <div class="row">
        <div class="icons input-field col s6 m6">
            <select class="input validate" name="design[gender]">
                <option value="" disabled selected>Select gender</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="genderless">genderless</option>
            </select>
        </div>
        <div class="input-field col s6 m6">
            <select class="icons input validate" name="design[season]">
                <option value="" disabled selected>Select season</option>
                <option value="spring">Spring</option>
                <option value="summer">Summer</option>
                <option value="autumn">Autumn</option>
                <option value="winter">Winter</option>
                <option value="no season">No season</option>
            </select>
        </div>
        <div class="input-field col s12">
            <%= f.text_field :title, null: false, autofocus: true, class:"input", length: "45", maxlength: "45" %>
            <%= f.label :title %>
        </div>
        <div class="input-field col s12">
            <%= f.text_area :description, null: false, autofocus: true, class:"input materialize-textarea", id: "textarea1", length: "120", maxlength: "120" %>
            <%= f.label :description %>
        </div>
    </div>
    <div class="file-field input-field">
        <div class="btn">
            <span>File</span>
            <%= f.file_field :image, class: "waves-light btn-large"%>
        </div>
        <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
        </div>
    </div>

    <div class="center" %>
        <button type="submit" class="button-new-design waves-effect waves-light btn-large">create design
            <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
        </button>
    </div>
    <%end%>
</div>

app/views/designs/season.html.erb
<% @designs.each do |design| %>
<%= design.title %>
<%end%>

app/views/designs/show.html.erb
<div class="row">
  <div id="modal1" class="modal">
  <%= render partial: "designs/edit"%>
</div>
    <div class="col s12 m6">
        <div class="card darken-1">
            <div class="card-content">
                <img Design <h class="responsive-img z-depth-4" <%= image_tag @design.image.url %> </div> </div> </div> <div class="col s12 m6"> <div class="card darken-1 z-depth-2"> <div class="card-content"> <span class="card-title"> Information</span> <p>name by designe:
                <%= @design.title %></h6>
            <p>
                <% if @design.season == "genderless" %>
            </h4>this design is the gender
            <%= @design.gender%>
            and has no season</h4>
        <p>
        <% else %>
        </h4>this design is the gender
        <%= @design.gender%>
        and their season
        <%= @design.season %></h4>
    <p>
        <% end %>
        <p>
            <h6>desciption:
                <%= @design.description %></h6>
            <p>
                <p>
                    <h6>creation date:
                        <%= @design.created_at.strftime("%d %b %y") %></h6>
                    <p>

                        <% @propetary.each do |propetary| %>
                    </div>
                    <div class="card-action">
                        <h6><a class="waves-effect waves-light btn" <%= link_to 'more designs by this designer', designer_path(propetary.id)%></h6>
                    </a>
                </p>
            </p>
        </div>
    </div>
</div>
<div class="col s12 m6">
    <div class="card darken-1 z-depth-2">
        <div class="card-content">
            <span class="card-title">Designer Information</span>
            <p>
                <h6>user since
                    <%= propetary.created_at.strftime("%d %b %y") %></h6>
                <p>
                    <p>
                        <h6>name by designer:
                            <%= propetary.name %></h6>
                        <p></div>
                        <div class="card-action"></div>
                    </div>
                </div>
            </div>
            <%=  commontator_thread(@design) %>

            <% if current_user.id == propetary.id%>
            <div class="fixed-action-btn horizontal click-to-toggle" style="bottom: 45px; right: 24px;">
                <a class="btn-floating btn-large blue">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </a>
                <ul>
                  <a class="waves-effect waves-light btn" href="#modal1">Modal</a>

                    <a class="btn-floating yellow" <%=link_to edit_design_path(@design), method: "get" do%><i class="material-icons">mode_edit</i></a>


                <% end %>
                <a  class="btn-floating blue darken-1" <%=link_to new_design_path, method: "get" do%><i class="material-icons">library_add</i>
            </a>
            <% end %>
            <a class="btn-floating red darken-1" <%= link_to design_path(@design), method: :delete, data: { confirm: "It will remove this design, are sure?" } do%> <i class="material-icons">delete</i>
        </a>
        <% end %>
    </ul>
</div>
<% end %>
<%end%>

app/views/designs/show_all.erb
<div class="row">
    <% @designs.each do |design| %>
    <div class="col s12 m4">
        <div class="circle-designs-card card ">
            <div class="card-image image-medium">
                <%= link_to design_path(design, design.user_id) do %>
                <%=image_tag design.image.url(:medium) %>
                <%end%>
            </div>
            <div class="card-content">
                <div class="col s12 m4 top">
                    <% ellipsis = design.title.bytesize  %>
                    <% if ellipsis == 9 %>
                    <%= design.title %>
                    <% elsif ellipsis < 9 %>
                    <%= design.title %>
                    <%else%>
                    <%= design.title.split("").values_at(0..8).join.ljust(12, "...")%>
                    <%end%>
                </div>
                <div class="col s12 m4 top">
                    <%= link_to like_path(design), method: :put do %>
                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                    <%end%>
                    <%= design.get_upvotes.size %>|
                    <%= link_to dislike_path(design), method: :put do %>
                    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                    <%= design.get_downvotes.size %>
                    <%end%>
                </div>
                <div class="col s12 m3 top">
                    <% @user = User.where(id: design.user_id).each do |user| %>
                    <%= link_to designer_path(user) do%>
                    <%=user.name%>
                    <%end%>
                    <%end%>
                </div>
                <div class="col s12 m1">
                    <%= "#{design.impressionist_count}" %>
                </div>
            </div>
        </div>
    </div>

    <%end%>

</div>
<%= paginate @designs %>