config/routes.rb
Rails.application.routes.draw do
    resources :subscribers
    # mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'registrations' }

    get '/' => 'application#index', as: 'index'
    get '/account' => 'users#show', as: 'account'
    get 'designs' => 'designs#show_all', as: 'designs'
    get 'designer/:id' => 'designs#designer', as: 'designer'
    post 'designs' => 'designs#create'

    get 'designs/filter' => 'designs#filter_gender'
    get 'designs/:gender' => 'designs#filter_season'

    get 'designs/:gender/:season' => 'designs#filter', as: 'filter'

    mount Commontator::Engine => '/commontator'

    delete 'design/:id/delete' => 'designs#destroy', as: 'destroy_design'

    resources :designs, path: 'design', except: [:index]
    put	'/design/:id/like' =>	'designs#upvote', as: 'like'
    put	'/design/:id/dislike' => 'designs#downvote', as: 'dislike'
end

app/views/layouts/_flash.html.erb
<% if flash[:error] %>

<div id="toast-container">

    <script type="text/javascript">
        Materialize.toast('<h5><%= flash[:error] %></h5>', 8000, 'red rounded')
    </script>

</div>

<%end%>

<% if flash[:success] %>

<div id="toast-container">

    <script type="text/javascript">
        Materialize.toast('<h5><%= flash[:success] %></h5>', 8000, 'yellow rounded')
    </script>

</div>

<%end%>

<% if flash[:notice] %>

<div id="toast-container">

    <script type="text/javascript">
        Materialize.toast('<h5><%= flash[:notice] %></h5>', 8000, 'blue rounded')
    </script>

</div>

<%end%>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text"><%=image_tag("logo", style: "width: 35px;")%>
                    <span class="lighten" style="font-size: 1.3rem; margin-left: -15px; font-weight: 700; font-family: Lato;">
                        <b class="blue-text">Designers</b>
                        <b class="white-text">Oportunity</b>
                    </span>
                </a>
            </h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
            <h5 class="white-text">support</h5>
            <ul>
                <li>
                    <a class="grey-text text-lighten-3" href="#!">about Designers Oportunity</a>
                </li>
                <li>
                    <a class="grey-text text-lighten-3" href="#!">how it works</a>
                </li>
                <li>
                    <a class="grey-text text-lighten-3" href="#!">FAQs</a>
                </li>
                <li>
                    <a class="grey-text text-lighten-3" href="#!">contact</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="footer-copyright">
    <div class="container">
        <a class="white-text" href="#">GitHub Project
            <i class="fa fa-github" style="color:white" aria-hidden="true"></i>
        </a>

        <div class="right list-group">
            <a class="list-group-item" href="https://facebook.com">
                <i class="fa fa-facebook-square fa-2x" style="color:white" aria-hidden="true"></i>
            </a>
            <a class="list-group-item" href="https://facebook.com">
                <i class="fa fa-google-plus fa-2x" style="color:white" aria-hidden="true"></i>
            </a>
            <a class="list-group-item" href="https://twitter.com">
                <i class="fa fa-twitter-square fa-2x" style="color:white" aria-hidden="true"></i>
            </a>
            <a class="list-group-item" href="https://linkedin.com">
                <i class="fa fa-linkedin-square fa-2x" style="color:white" aria-hidden="true"></i>
            </a>
            <a class="list-group-item" href="https://facebook.com">
                <i class="fa fa-github fa-2x" style="color:white" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<main>
    <header>
        <nav>

            <% if controller.controller_name == "application" && controller.action_name == "index" %>
            <div class="nav-wrapper index">
                <%else%>
                <div class="nav-wrapper">
                    <%end%>
                    <%=link_to index_path, id: "logo-container" do%>
                    <%= image_tag("logo", style: "height: 28px; vertical-align: middle; margin-top: -7px; margin-left: 4px;" )%>
                    <span class="lighten" style="font-size: 1.3rem; margin-left: -10px; font-weight: 700; font-family: Lato;">
                        <b class="blue-text">Designers</b>
                        <b class="white-text">Oportunity</b>
                    </span>

                    <%end%>

                    <ul class="right hide-on-med-and-down">
                        <%if current_user.nil?%>

                    <a class=" waves-effect waves-light btn " <%=link_to "login", new_user_session_path %></a>
                <a class=" waves-effect waves-light btn " <%= link_to "sign up", new_user_registration_path %></a>

                <%else %>

            <a class=" waves-effect waves-light btn" <%=link_to "designs", designs_path %></a>
        <a class=" waves-effect waves-light btn" <%=link_to "account", account_path %></a>
    <a class=" waves-effect waves-light btn" <%=link_to "new design", new_design_path, method: 'get'%></a>
    <% end %>
</ul>

<ul class="side-nav" id="mobile-demo">
    <%if current_user.nil?%>

    <a class=" waves-effect waves-light btn" <%=link_to "login", new_user_session_path %></a>
      <a class=" waves-effect waves-light btn" <%= link_to "sign up", new_user_registration_path %></a>

    <%else %>

    <a class=" waves-effect waves-light btn" <%=link_to "designs", designs_path %></a>
      <a class=" waves-effect waves-light btn" <%=link_to "account", account_path %></a>
        <a class=" waves-effect waves-light btn" <%=link_to "new design", new_design_path, method: 'get'%></a>

  <% end %>
</ul>

<a href="" data-activates="mobile-demo" class="button-collapse"><i class="fa fa-bars" aria-hidden="true"></i></a>


</nav>
</header>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>DesignersOportunity</title>
        <%= csrf_meta_tags %>
        <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>

    <body>
        <main>

            <%= javascript_include_tag "materialize" %>
            <%= render 'layouts/header' unless params[:controller] == "devise/sessions" or "registrations" and params[:action] == "new"  %>
            <%= render partial: "layouts/flash" %>
            <%= yield %>
        </main>
        <%= render 'layouts/footer' unless params[:controller] == "devise/sessions" or "devise/registrations" and params[:action] == "new" %>

    </body>
</html>

app/views/layouts/footer.html.erb
<footer class="page-footer">
     <div class="container">
       <div class="row">
         <div class="col l6 s12">
           <h5 class="white-text">Footer Content</h5>
           <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
         </div>
         <div class="col l4 offset-l2 s12">
           <h5 class="white-text">Links</h5>
           <ul>
             <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
             <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
             <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
             <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
           </ul>
         </div>
       </div>
     </div>
     <div class="footer-copyright">
       <div class="container">
       © 2014 Copyright Text
       <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
       </div>
     </div>
   </footer>

app/views/layouts/header.html.erb
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>
        